apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cqrs-command-order
  name: cqrs-command-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cqrs-command-order
  strategy: {}
  template:
    metadata:
      labels:
        app: cqrs-command-order
    spec:
      containers:
      - image: dleurs/cqrs-command-order:IMAGETAG
        name: cqrs-command-order
        ports:
        - containerPort: 8081
        env:
          - name: PORT
            value: "8081"
          #- name: NODE_ENV
          #  value: "production"
          - name: ORDERDBURL
            value: "http://cqrs-order-db-svc.default.svc.cluster.local"
          - name: PROCESSDATAURL
            value: "http://cqrs-process-data-svc.default.svc.cluster.local"
        resources: 
          requests:
            memory: "50Mi"
            cpu: "0.05"
          limits:
            memory: "100Mi"
            cpu: "0.1"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cqrs-command-order
  name: cqrs-command-order-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
    name: http
  selector:
    app: cqrs-command-order
  type: ClusterIP
status:
  loadBalancer: {}