apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: RENAME
  name: RENAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RENAME
  strategy: {}
  template:
    metadata:
      labels:
        app: RENAME
    spec:
      containers:
      - image: dleurs/RENAME:1.0.0
        name: RENAME
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: DBURL
            value: "mongodb://root:GOMy2VxWaH@release-1-mongodb.default.svc.cluster.local:27017/todoProject?authSource=admin"
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: RENAME
  name: RENAME-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: RENAME
  type: LoadBalancer
status:
  loadBalancer: {}