apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cqrs-k8s-serviceInterface
  name: cqrs-k8s-serviceInterface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cqrs-k8s-serviceInterface
  strategy: {}
  template:
    metadata:
      labels:
        app: cqrs-k8s-serviceInterface
    spec:
      containers:
      - image: dleurs/cqrs-k8s-serviceInterface:1.0.0
        name: cqrs-k8s-serviceInterface
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: QUERYURL
            value: "http://cqrs-k8s-query-svc.default.svc.cluster.local"
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cqrs-k8s-serviceInterface
  name: cqrs-k8s-serviceInterface-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: cqrs-k8s-serviceInterface
  type: LoadBalancer
status:
  loadBalancer: {}