apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-docker-tr
spec:
  serviceAccountName: tekton-sa
  taskRef:
    name: build-docker-task
  inputs:
    resources:
      - name: git-source-pr
        resourceRef:
          name: git-source-pr
    params:
      - name: pathToDockerFile
        value: /workspace/docker-source/dispatcher/Dockerfile
      - name: pathToContext
        value: /workspace/git-source-pr
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: docker-target-pr