apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source-pr
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/dleurs/cqrs-kubernetes-nodejs