apiVersion: serving.knative.dev/v1 
kind: Service
metadata:
  name: cqrs-dispatcher 
  namespace: default  
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: dleurs/cqrs-dispatcher:1.1.4 
          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"
          env:
            #- name: PORT
            #  value: "8080"
            #- name: NODE_ENV
            #  value: "production" => Not working with prod
            - name: COMMANDORDERURL
              value: "http://cqrs-command-order.default.svc.cluster.local"
            - name: QUERYORDERBURL
              value: "http://cqrs-query-order.default.svc.cluster.local"