apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
  labels:
    visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"
          env:
            - name: TARGET
              value: "Go Sample v1"
