apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: cqrs-process-data # The name of the app
  namespace: default # The namespace the app will use
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: dleurs/cqrs-process-data:1.0.0 # Reference to the image of the app
          #ports: => reserved in knative
          #- containerPort: 8080
          env:
            #- name: PORT
            #  value: "8080"
            #- name: NODE_ENV
            #  value: "production" => Not working with prod
            - name: ORDERDBURL
              value: "http://cqrs-order-db.default.svc.cluster.local"
            - name: STATSORDERDBURL
              value: "http://cqrs-stats-order-db.default.svc.cluster.local"