apiVersion: serving.knative.dev/v1 
kind: Service
metadata:
  name: cqrs-process-data 
  namespace: default 
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: dleurs/cqrs-process-data:1.0.0 
          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"
          env:
            #- name: PORT
            #  value: "8080"
            #- name: NODE_ENV
            #  value: "production" => Not working with prod
            - name: ORDERDBURL
              value: "http://cqrs-order-db.default.svc.cluster.local"
            - name: STATSORDERDBURL
              value: "http://cqrs-stats-order-db.default.svc.cluster.local"