apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: cqrs-stats-order-db # The name of the app
  namespace: default # The namespace the app will use
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: dleurs/cqrs-stats-order-db:1.0.0 # Reference to the image of the app