apiVersion: serving.knative.dev/v1 
kind: Service
metadata:
  name: cqrs-stats-order-db 
  namespace: default 
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: dleurs/cqrs-stats-order-db:1.0.0 # Reference to the image of the app
          #resources:
          #  requests:
          #    memory: "500Mi"
          #    cpu: "250m"
          #  limits:
          #    memory: "1Gi"
          #    cpu: "500m"